LocalIP: 127.0.0.1
spring:
  datasource:
    url: jdbc:mysql://${LocalIP}:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: admin
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
server:
  port: 80