spring:
  datasource:
    platform: h2
#    data: classpath: data.sql  .sql need to be be set when the file is generating,and this ddl-auto£º none
#    schema: classpath:schema.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root: warn
    org:
      hibernate: info
