spring:
  rabbitmq:
    host: 39.106.184.220
    username: admin
    password: admin
  data:
    mongodb:
      host: 39.106.184.220
      port: 8998

logging:
  config:
    root: error

server:
  port: 8080
