mysql:
  datasource:
    test1:
      url: jdbc:mysql://localhost:3306/bootdb?useUnicode=true&characterEncoding=utf-8
      username: root
      password: admin
      min-pool-size: 3
      max-pool-size: 25
      max-lifetime: 20000
      borrow-connection-timeout: 30
      login-timeout: 30
      maintenance-interval: 60
      max-idle-time: 60
      test-query: select 1
    test2:
      url: jdbc:mysql://localhost:3306/dev?useUnicode=true&characterEncoding=utf-8
      username: root
      password: admin
      min-pool-size: 3
      max-pool-size: 25
      max-lifetime: 20000
      borrow-connection-timeout: 30
      login-timeout: 30
      maintenance-interval: 60
      max-idle-time: 60
      test-query: select 1